package soap_server_notify.IControllerNotifyPackage;

/**
* soap_server_notify/IControllerNotifyPackage/BuyDTOHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* Monday, August 8, 2022 6:38:02 AM COT
*/

public final class BuyDTOHolder implements org.omg.CORBA.portable.Streamable
{
  public soap_server_notify.IControllerNotifyPackage.BuyDTO value = null;

  public BuyDTOHolder ()
  {
  }

  public BuyDTOHolder (soap_server_notify.IControllerNotifyPackage.BuyDTO initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = soap_server_notify.IControllerNotifyPackage.BuyDTOHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    soap_server_notify.IControllerNotifyPackage.BuyDTOHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return soap_server_notify.IControllerNotifyPackage.BuyDTOHelper.type ();
  }

}
