package soap_server_notify.IControllerNotifyPackage;


/**
* soap_server_notify/IControllerNotifyPackage/BuyDTOHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* Monday, August 8, 2022 6:38:02 AM COT
*/

abstract public class BuyDTOHelper
{
  private static String  _id = "IDL:soap_server_notify/IControllerNotify/BuyDTO:1.0";

  public static void insert (org.omg.CORBA.Any a, soap_server_notify.IControllerNotifyPackage.BuyDTO that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static soap_server_notify.IControllerNotifyPackage.BuyDTO extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [7];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[0] = new org.omg.CORBA.StructMember (
            "numberId",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "idType",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_double);
          _members0[2] = new org.omg.CORBA.StructMember (
            "priceBuy",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[3] = new org.omg.CORBA.StructMember (
            "placeBuy",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[4] = new org.omg.CORBA.StructMember (
            "paymentMethod",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[5] = new org.omg.CORBA.StructMember (
            "dateBuy",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[6] = new org.omg.CORBA.StructMember (
            "nitCompany",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (soap_server_notify.IControllerNotifyPackage.BuyDTOHelper.id (), "BuyDTO", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static soap_server_notify.IControllerNotifyPackage.BuyDTO read (org.omg.CORBA.portable.InputStream istream)
  {
    soap_server_notify.IControllerNotifyPackage.BuyDTO value = new soap_server_notify.IControllerNotifyPackage.BuyDTO ();
    value.numberId = istream.read_long ();
    value.idType = istream.read_string ();
    value.priceBuy = istream.read_double ();
    value.placeBuy = istream.read_string ();
    value.paymentMethod = istream.read_string ();
    value.dateBuy = istream.read_string ();
    value.nitCompany = istream.read_long ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, soap_server_notify.IControllerNotifyPackage.BuyDTO value)
  {
    ostream.write_long (value.numberId);
    ostream.write_string (value.idType);
    ostream.write_double (value.priceBuy);
    ostream.write_string (value.placeBuy);
    ostream.write_string (value.paymentMethod);
    ostream.write_string (value.dateBuy);
    ostream.write_long (value.nitCompany);
  }

}
