package soap_server_notify.IControllerNotifyPackage;


/**
* soap_server_notify/IControllerNotifyPackage/BuyDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* Monday, August 8, 2022 6:38:02 AM COT
*/

public final class BuyDTO implements org.omg.CORBA.portable.IDLEntity
{
  public int numberId = (int)0;
  public String idType = null;
  public double priceBuy = (double)0;
  public String placeBuy = null;
  public String paymentMethod = null;
  public String dateBuy = null;
  public int nitCompany = (int)0;

  public BuyDTO ()
  {
  } // ctor

  public BuyDTO (int _numberId, String _idType, double _priceBuy, String _placeBuy, String _paymentMethod, String _dateBuy, int _nitCompany)
  {
    numberId = _numberId;
    idType = _idType;
    priceBuy = _priceBuy;
    placeBuy = _placeBuy;
    paymentMethod = _paymentMethod;
    dateBuy = _dateBuy;
    nitCompany = _nitCompany;
  } // ctor

} // class BuyDTO
