package soap_server_notify;


/**
* soap_server_notify/IControllerNotifyHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* Monday, August 8, 2022 6:38:02 AM COT
*/

abstract public class IControllerNotifyHelper
{
  private static String  _id = "IDL:soap_server_notify/IControllerNotify:1.0";

  public static void insert (org.omg.CORBA.Any a, soap_server_notify.IControllerNotify that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static soap_server_notify.IControllerNotify extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (soap_server_notify.IControllerNotifyHelper.id (), "IControllerNotify");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static soap_server_notify.IControllerNotify read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_IControllerNotifyStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, soap_server_notify.IControllerNotify value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static soap_server_notify.IControllerNotify narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof soap_server_notify.IControllerNotify)
      return (soap_server_notify.IControllerNotify)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      soap_server_notify._IControllerNotifyStub stub = new soap_server_notify._IControllerNotifyStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static soap_server_notify.IControllerNotify unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof soap_server_notify.IControllerNotify)
      return (soap_server_notify.IControllerNotify)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      soap_server_notify._IControllerNotifyStub stub = new soap_server_notify._IControllerNotifyStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
