package soap_server_notify;


/**
* soap_server_notify/IControllerNotifyPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* Monday, August 8, 2022 6:38:02 AM COT
*/

public abstract class IControllerNotifyPOA extends org.omg.PortableServer.Servant
 implements soap_server_notify.IControllerNotifyOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("notifyAlert", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // soap_server_notify/IControllerNotify/notifyAlert
       {
         soap_server_notify.IControllerNotifyPackage.BuyDTO objBuy = soap_server_notify.IControllerNotifyPackage.BuyDTOHelper.read (in);
         boolean $result = false;
         $result = this.notifyAlert (objBuy);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:soap_server_notify/IControllerNotify:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public IControllerNotify _this() 
  {
    return IControllerNotifyHelper.narrow(
    super._this_object());
  }

  public IControllerNotify _this(org.omg.CORBA.ORB orb) 
  {
    return IControllerNotifyHelper.narrow(
    super._this_object(orb));
  }


} // class IControllerNotifyPOA
