package soap_server_notify;


/**
* soap_server_notify/IControllerNotifyOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* Monday, August 8, 2022 6:38:02 AM COT
*/

public interface IControllerNotifyOperations 
{
  boolean notifyAlert (soap_server_notify.IControllerNotifyPackage.BuyDTO objBuy);
} // interface IControllerNotifyOperations
