package soap_server_notify;

/**
* soap_server_notify/IControllerNotifyHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* Monday, August 8, 2022 6:38:02 AM COT
*/

public final class IControllerNotifyHolder implements org.omg.CORBA.portable.Streamable
{
  public soap_server_notify.IControllerNotify value = null;

  public IControllerNotifyHolder ()
  {
  }

  public IControllerNotifyHolder (soap_server_notify.IControllerNotify initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = soap_server_notify.IControllerNotifyHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    soap_server_notify.IControllerNotifyHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return soap_server_notify.IControllerNotifyHelper.type ();
  }

}
