package soap_server_notify;


/**
* soap_server_notify/IControllerNotify.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* Monday, August 8, 2022 6:38:02 AM COT
*/

public interface IControllerNotify extends IControllerNotifyOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface IControllerNotify
